### ISSUE TITLE
2025f3f Not compiling on Linux

### ISSUE THREAD

**Issue by cullenspub** [VCVRack/AudibleInstruments#11]
For a clean build of all VCVRack and plugins, AudibleInstruments 2025f3f fails during compile. The last commit to build was ad9fe26.

**Error**
```
g++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/Links.cpp.o src/Links.cpp
In file included from src/Braids.cpp:6:0:
./eurorack/braids/signature_waveshaper.h: In member function ‘void braids::SignatureWaveshaper::Init(uint32_t)’:
./eurorack/braids/signature_waveshaper.h:68:46: error: invalid operands of types ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ and ‘int’ to binary ‘operator>>’
           (8192 + (sigmoid_strength * abs(x) >> 5));
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../../compile.mk:49: recipe for target 'build/src/Braids.cpp.o' failed
```

**Environment**:
GNU Make: 4.1
gcc version 6.3.1
cmake version 3.9.0
Linux: 4.9.11-100.rt9.1.fc24.ccrma.x86_64+rt #1 SMP PREEMPT RT Sat Feb 25 23:30:31 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cullenspub** [comment]
My apologies - this is clearly a duplicate. 
Adding
```
int16_t abs(int16_t x) {return abs((int32_t)x);}
include "braids/signature_waveshaper.h"
```
 in Braids.cpp fixes the problem.

**Comment by AndrewBelt** [comment]
I should really fork Olivier's source and fix it there

**Comment by titovm** [comment]
Having the same issue, but can't figure out, where in Braids.cpp should put these lines into.
Doing this in the end of file, doesn't fix it.

**Comment by cullenspub** [comment]
In the file Braids.cpp, insert:
int16_t abs(int16_t x) {return abs((int32_t)x);}
Before the existing line
include "braids/signature_waveshaper.h"

**Comment by AndrewBelt** [comment]
Fixed by forking Mutable Instruments' eurorack repo and making changes to the source itself. Updated code to match in 54d4222.

I don't know what kind of magic you'll need to do to re-checkout the new repo. Maybe `git pull`, `git submodule sync --recursive`, `git submodule update --recursive` will do it. Maybe you'll have to delete the AudibleInstruments directory and clone it again.
