### ISSUE TITLE
Veils is no longer unipolar

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/AudibleInstruments#111]
On the v1 Rack build, the Veils clone has correct, unipolar gain knobs like the Veils hardware. On the v2 Rack build, the knobs are now bipolar. This seems like an inappropriate change since Veils is intended to be a VCA mixer while Blinds is the polarizing mixer.

**Comment by mhetrick** [comment]
Here is the offending commit: https://github.com/VCVRack/AudibleInstruments/commit/bb1167e3974ad00ad2f8bf4c32ebe26589b312b6

It looks like the Veils labels were copied from Blinds and not corrected to be unipolar after.

**Comment by AndrewBelt** [comment]
Nice catch! Fixed in 7225bf8
