### ISSUE TITLE
Macro Oscillator LED Shows CSAW Regardless of Model

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [VCVRack/AudibleInstruments#112]
Using Macro Oscillator, regardless of what model is selected (either via the menu or turning the knob), the LED shows CSAW.

Using VCV Rack 219bbaf1 and the Audible Instruments built for 2.git.219bbaf1 versions on Windows 10.

**Comment by AndrewBelt** [comment]
It works for me. Are you sure your rack engine is running (rendering audio frames)?

**Comment by FunkybotsEvilTwin** [comment]
Yes, that was exactly it! Was just checking out the look of the new Audible builds and didn't realize the audio device wasn't enabled. As soon as I select a device the LED updates. Apologies for the false alarm.
