### ISSUE TITLE
V2.0 crashes Ableton when reloading project

### ISSUE THREAD

**Issue by aaronstatic** [VCVRack/AudibleInstruments#113]
Any module that uses a font to display text seems to be crashing Ableton when a project is loaded containing a VCV Rack 2.0 VST and the module.

As per the 1.0 to 2.0 migration guide the fonts should be loaded locally in the draw call. But the Audible modules such as Braids are still loading them in the constructor. 

https://github.com/VCVRack/AudibleInstruments/blob/v2/src/Braids.cpp

This seems to be causing Ableton to crash when trying to reload the project. I had the same issue with my modules. Only after removing the entire Audible plugin from the user plugins directory can the project be loaded again in Ableton.

I can put this into a pull request if you want but I thought it might be a simple enough change for you to do.

**Comment by AndrewBelt** [comment]
Thanks, fixed in 43e1c2e!
