### ISSUE TITLE
Frames data saving

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/AudibleInstruments#16]
I just had a long session with the wonderfull Frames module. I only noted that after saving and loading my patch again, Frames did not recall all programmed frames.
Are there plans to dump the frame data into the json segment of Frames? That would be so great!

Thanks,
Martin

**Comment by AndrewBelt** [comment]
Ha, completely forgot! Should be easy to add that feature.

**Comment by phdsg** [comment]
i see, you added the parameter saving for most of the menu options.
the 'response curve' option doesn't change at all, though.

**Comment by AndrewBelt** [comment]
The response curve parameter is really just a result of OTAs from being exponential and wanting to smoothly interpolate between its classic behavior and linear (which most people want). So I'm not opposed to removing it.
I might as well keep it though, although I'm setting the values incorrectly.

**Comment by AndrewBelt** [comment]
Looks like everything is good now after fb1cf26
