### ISSUE TITLE
Branches Input Normalization not working again

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/AudibleInstruments#21]
The rewritten callback in commit 616fd1fe63ff07c2ab9e500149134c4b80c1f9b3 (https://github.com/VCVRack/AudibleInstruments/commit/616fd1fe63ff07c2ab9e500149134c4b80c1f9b3#diff-0328616b49c8f8fbc3a53902747de5bb) removed the normalization between input channels on Branches.

**Comment by AndrewBelt** [comment]
Thanks, fixed again in 80ca311
