### ISSUE TITLE
Timbre input braids/macro oscillator not working

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/AudibleInstruments#3]
The input of the braids module is non-functional.

**Comment by AndrewBelt** [comment]
I'll take a second look at this, but I'm pretty sure it works, and I'm using it my patches. Maybe I've set the scaling to a too-small value?

**Comment by sanderbaan** [comment]
Sorry my mistake, forgot that the timbre input works in combination with the modulation knob :) not like the Color input...
