### ISSUE TITLE
Tides & Sheep frequency doesn't change

### ISSUE THREAD

**Issue by mhetrick** [VCVRack/AudibleInstruments#31]
On Mac 10.12, latest dev:

-Turning the frequency knob on Tides or Sheep does not seem to affect the output.
-In Sheep mode, I can no longer change the wave bank.
-In Tides mode, I cannot seem to change the behavior mode (AD/AHD/Loop).

**Comment by AndrewBelt** [comment]
My guess is that https://github.com/VCVRack/AudibleInstruments/commit/e8528e28bffeeb6b5f192592cc23e0d7ff61de22 breaks ABI compatibility with itself, so `make clean` and `make`.

**Comment by mhetrick** [comment]
Fixed with `make clean` and `make`
