### ISSUE TITLE
Adding "Texture synthesizer" makes application crashes.

### ISSUE THREAD

**Issue by killkrt** [VCVRack/AudibleInstruments#34]
Hi,

I'm using updated revision (a17ae2c) of VCVRack and Audible Instruments plugins (715f977).
Every time that I try to add "Texture synthesizer" the application crashes.
It happens only whit this module, others modules work perfectly.

Thank you.

Tested on:
OS: Arch Linux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
OpenGL: 4.6.0 NVIDIA 387.34

and

OS: macOS 10.12.6

**Comment by cschol** [comment]
Is this still an issue? Can you provide a backtrace of the crash?

**Comment by killkrt** [comment]
After the last update I cannot event compile it anymore.
I'm getting lot of errors compiling `Frames.cpp`.

**Comment by AndrewBelt** [comment]
Are the AudibleInstruments and all its submodules up to date?

**Comment by killkrt** [comment]
Yes, I executed `git pull` and `git submodule update --init --recursive` under 'AudibleInstruments` folder (and also under `plugins` folder, just in case)

**Comment by cschol** [comment]
What branch are you trying to compile here? `v0.5` or `master`?

**Comment by killkrt** [comment]
I was working on `v0.5` branch.
BTW making a fresh clone **solved** the issue, cannot figure out why (no local changes).

So, sorry, please close this issue.

Thank you.
