### ISSUE TITLE
Modal Synthesizer (v0.5.0) tagged as "Reverb"

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/AudibleInstruments#35]
Hi, from "Add module" in VCV Rack v0.5.1, the module **Modal Synthesizer** is tagged as Reverb. Is it normal? TIA

**Comment by AndrewBelt** [comment]
It does reverb, so I think it's appropriate.

**Comment by DomiKamu** [comment]
Hi Andrew, why you've closed this ticket? 

The Modal Synthesizer isn't a pure reverb, it's mainly a sound generator / synthesizer, despite it provides some effects (such reverb), too. 

By this way, only "Reverb" as tag isn't appropriate. 

Thanks to take this in consideration. 

Dominique Camus 

----- Mail original -----

De: "Andrew Belt" <notifications@github.com> 
À: "VCVRack/AudibleInstruments" <AudibleInstruments@noreply.github.com> 
Cc: "DomiKamu" <docam@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 14 Janvier 2018 21:39:08 
Objet: Re: [VCVRack/AudibleInstruments] Modal Synthesizer (v0.5.0) tagged as "Reverb" (#35) 


It does reverb, so I think it's appropriate.

**Comment by AndrewBelt** [comment]
I closed your ticket because I disagree with your suggestion.

**Comment by AndrewBelt** [comment]
On second thought, since there's now a PHYSICAL_MODELING_TAG, I've removed reverb.

**Comment by DomiKamu** [comment]
Excellent idea! of course, be sure it's not urgent (or something like), but I'm (too) perfectionnist, sorry. 
And, of course, I can easily understand you've many important stuff around VCV Rack itself. 

Since you implement PHYSICAL_MODELING_TAG, of course it will be perfect to use as first tag, but you'll can also use EFFECT_TAG as second tag, it's appropiate IMO. 

Regards, 

Dominique CAMUS 

----- Mail original -----

De: "Andrew Belt" <notifications@github.com> 
À: "VCVRack/AudibleInstruments" <AudibleInstruments@noreply.github.com> 
Cc: "DomiKamu" <docam@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 16 Janvier 2018 08:47:32 
Objet: Re: [VCVRack/AudibleInstruments] Modal Synthesizer (v0.5.0) tagged as "Reverb" (#35) 


On second thought, since there's now a PHYSICAL_MODELING_TAG, I've removed reverb.
