### ISSUE TITLE
715f977 not compiling Windows 7

### ISSUE THREAD

**Issue by LKHSogpit** [VCVRack/AudibleInstruments#37]
```
Makefile:55: warning: overriding recipe for target 'dist'
../../plugin.mk:36: warning: ignoring old recipe for target 'dist'
g++ -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/Clouds.cpp.o src/Clouds.cpp
src/Clouds.cpp:7:10: fatal error: clouds/dsp/granular_processor.h: No such file or directory
 #include "clouds/dsp/granular_processor.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:54: build/src/Clouds.cpp.o] Error 1
```

**Comment by AndrewBelt** [comment]
I think you need to check out the submodules. https://github.com/VCVRack/AudibleInstruments/blob/v0.5/README.md#building

**Comment by LKHSogpit** [comment]
Just looking at the code there was scratching my head how the Mult and Utility modules were not named. Tried that command in MSYS2 just before posting gave this error might not be doing it right idk.

from the Plugins/AudibleInstruments directory
entering: git submodule update --init --recursive returning:
```
': not a valid identifierline 88: export: `dashless
```

**Comment by AndrewBelt** [comment]
You can ignore that warning message. Does it build now?

**Comment by LKHSogpit** [comment]
Tried the commands
```
mv /mingw64/bin/envsubst.exe /mingw64/bin/envsubst.exe.old
```
```
pacman -S gettext
```

Update the files then tried again
```
git submodule update --init --recursive
```
Do not get the "88" error nothing of any kind just goes back to the directory. Doing make again still give the error associated with the dependicies.

**Comment by LKHSogpit** [comment]
Just deleted and re-cloned think it might be working now.

**Comment by AndrewBelt** [comment]
Okay, closing since this is solved. Reopen if not.
