### ISSUE TITLE
Meta Modulator calling wrong panel

### ISSUE THREAD

**Issue by davephillips** [VCVRack/AudibleInstruments#46]
Fedora 23 Linux
Rack 0.6.0 dev

The Meta Modulator graphic is wrong, it's calling the Quad-polarizer SVG (see attached image).

![notmetamodulatorsvg](https://user-images.githubusercontent.com/7815938/36708044-28da36c8-1b3f-11e8-8550-1ce3d07ec72e.png)

**Comment by AndrewBelt** [comment]
Fixed 2fc0a05
