### ISSUE TITLE
Elements alternative synthesis models

### ISSUE THREAD

**Issue by kiwanowski** [VCVRack/AudibleInstruments#5]
https://mutable-instruments.net/modules/elements/firmware/ - please add an option to enable the alternative synthesis models as described in the link

**Comment by AndrewBelt** [comment]
This should be pretty easy by adding a right click menu with the three modes.

**Comment by AndrewBelt** [comment]
8b3c82b0916c4c96eafddee758d96cbfb1fbf2fa
