### ISSUE TITLE
Bernoulli Gate: Channel "Toggle" state reverts to "Latch" on opening of saved patch

### ISSUE THREAD

**Issue by patman023** [VCVRack/AudibleInstruments#54]
as per title.

all plugins updated to latest version.

[apr30-2-b.zip](https://github.com/VCVRack/AudibleInstruments/files/1965661/apr30-2-b.zip)

**Comment by AndrewBelt** [comment]
Thanks, fixed in dd25b17

**Comment by patman023** [comment]
Thanks!
