### ISSUE TITLE
Macro Osc 2 -  LPG Edit Mode issue/Feature request

### ISSUE THREAD

**Issue by n6smith** [VCVRack/AudibleInstruments#55]
When switching to LPG Edit mode and editing the LPG setting... if you then return to normal mode...  the sound you were editing the LPG for,  isnt restored but changes to the now current position of the knobs that were moved to edit the LPG. Is there a way this can be prevented otherwise editing the LPG must be the very last thing you do  to prevent this and once editing the LPG is done,  you cannot go back to normal mode without affecting the sound/waveform position etc?

**Comment by AndrewBelt** [comment]
In Rack 1.0, ParamWidgets will read its value directly from a Param, so it will be possible to move knobs around without hacks.

**Comment by n6smith** [comment]
Ah.. I can see how that would then resolve this kind of issue. Ok.. Makes sense and thanks as always Andrew. Case Closed.
