### ISSUE TITLE
(Clouds) Texture Synthesizer -- Reverb only applied to granulated audio

### ISSUE THREAD

**Issue by brendyman** [VCVRack/AudibleInstruments#60]
Hello,

I would like to point out an issue with the Audible instruments clone of Clouds:

In the actual, physical Clouds module, the reverb is applied to raw incoming audio AND granulated audio, allowing the user to use Clouds solely as a reverb effect if desired. 

In the VCV clone, the reverb is only applied to the granulated audio, which means the reverb is not audible at all if the granulator Wet/Dry blend is set to 0. 

Is this fixable?

**Comment by AndrewBelt** [comment]
I don't have Clouds anymore. Can one other person confirm before I make this breaking change?

**Comment by brendyman** [comment]
I found an example of someone demonstrating Clouds only as a reverb effect in this video: 

https://youtu.be/I-hTki9f3S8?t=17m51s

Density and Texture are both set to 12 o'clock, which means the audio is not being granulated at all -- reverb is just being applied to the incoming audio.

I used to own clouds and it was my go-to reverb effecrt. I had to sell most of my modules unfortunately, so I was thrilled to discover VCV rack and Audible instruments. I'd love to have that functionality again

**Comment by cschol** [comment]
Per Olivier (in 2017) the reverb is never applied to the dry signal, see below. I looked at the relevant code and dry really means DRY. Always.

![screen shot 2018-09-23 at 1 14 58 pm](https://user-images.githubusercontent.com/624427/45931954-d81f4c80-bf32-11e8-89e4-9595c412bbf2.png)

Reference:
https://forum.mutable-instruments.net/t/clouds-reverb-not-working-pls-help/12713/4

**Comment by brendyman** [comment]
Did you watch the video linked in my previous comment? The reverb is clearly being applied to the non-granulated signal. I remember this functionality clearly from when I owned clouds. I used it solely as a reverb ALL the time. I know I'm not crazy.

I understand that it's clearly always dry in the code but I'm also wondering how I (and so many other users as I've been able to see on YouTube) was able to use it as just a reverb. I guess it will remain a mystery.

**Comment by cschol** [comment]
From the panel and the knobs this could also be a DIY Clouds with a custom firmware. That does not explain your use case. Planning on building one here in the near future. I'll let you know what I find.

**Comment by brendyman** [comment]
Wait. I figured it out, and now I feel like an idiot. I had the parasites firmware on it.

From the parasites firmware page:

"Put the post-processing reverb after dry/wet, so that it also affects the dry signal (so you can use Clouds as a simple reverb plus its main function)"

**Comment by AndrewBelt** [comment]
Okay, thanks for looking into it.
