### ISSUE TITLE
Macro Osc 2 - Model CV

### ISSUE THREAD

**Issue by lnikj** [VCVRack/AudibleInstruments#61]
This is very probably a feature not a bug.

The model modulation responds only to 0-5v, not 0-10v. Is that intended?

**Comment by AndrewBelt** [comment]
It responds to +/-5V, which is documented in https://mutable-instruments.net/modules/plaits/

**Comment by lnikj** [comment]
Thanks. I missed that. I can see that was thinking about this control in the wrong way. I'm trying to sequence model changes and was expecting absolute voltages to correspond to the 16 choices. Feature not bug. Sorry.
