### ISSUE TITLE
Marbles not available

### ISSUE THREAD

**Issue by Edin72** [VCVRack/AudibleInstruments#63]
Hi there

Maybe I don't understand correctly regarding the Marbles module. Few months ago I bought the Plaits for 20$ and now I want to buy also the new Marbles but I can't figure it out how. 
Can you please help?

Best regards
Edin

**Comment by AndrewBelt** [comment]
Update your plugins. Marbles (Random Sampler) is in Audible Instruments Preview 0.6.2.

**Comment by Edin72** [comment]
I have done it several times but only the Plaits is visable.

**Comment by Edin72** [comment]
I've found it! It was still in zip file...not extracted. Many thanks!
