### ISSUE TITLE
Plaits: Outputs inverted

### ISSUE THREAD

**Issue by cschol** [VCVRack/AudibleInstruments#65]
The outputs (`OUT` and `AUX`) on the `Plaits` module seem to be inverted.

I ran a **real** `Plaits` into an Expert Sleepers `ES-8` (blue) and compared the waveforms to the `Plaits` module (purple):

![screen shot 2018-09-23 at 11 43 45 am](https://user-images.githubusercontent.com/624427/45931108-2e39c300-bf26-11e8-9b40-4bca0b3efa94.png)

Per the schematic, it actually looks like the physical module has inverting opamp circuitry on the outputs.

The Rack module also has slightly less output voltage, but that is a minor issue (left: physical module, right: Rack module):

![screen shot 2018-09-23 at 11 54 58 am](https://user-images.githubusercontent.com/624427/45931183-89b88080-bf27-11e8-98ee-7958d2fa6016.png)

**Comment by AndrewBelt** [comment]
Thanks, fixed in 5af180a
