### ISSUE TITLE
Build on macOS 10.12.6

### ISSUE THREAD

**Issue by lazzarello** [VCVRack/AudibleInstruments#7]
Things I did to get this repo to build

```
git submodule update --init
cd eurorack
git submodule update --init
cd ..
make
```

Soooo many submodules  :)

**Comment by AndrewBelt** [comment]
`git submodule update --init --recursive` also works

**Comment by alexisdel79** [comment]
It doesn't work properly on OS X Yosemite. It doesn't show the connectors nor knobs in any module.

**Comment by AndrewBelt** [comment]
@alexisdel79 Your issue relates to #17.

Also, I'm closing this issue since it's "resolved".
