### ISSUE TITLE
1.1.5 update causes Clouds (aka Texture Synth) to not emit any sound

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/AudibleInstruments#82]
I have tried absolutely everything but since 1.1.5 Rack update Clouds is acting normally, but outputs are silent. I have used it fine before 1.1.5 update, but since nothing seems to make it make any sound on outputs.

Mac OS X 10.11.6, Rack 1.1.5

**Comment by SteveRussell33** [comment]
Try this patch: [NoiseDrone.zip](https://github.com/VCVRack/AudibleInstruments/files/3729717/NoiseDrone.zip)

**Comment by fractalgee** [comment]
Thanks @SteveRussell33 ! I tried to recreate the issue and all working again, weird, as no update of it happened. So given I didn't save the nonworking patches I have no clue what the issue might have been but seems to have disappeared. I don't believe in magic so am a bit at a loss what might have made it work again as well. Oh well, the adventures of patching. Closing this as no longer ocurring

**Comment by SteveRussell33** [comment]
Glad you got it working again. I was going to say if that patch didn't work, not much will!
